version: "3.8"
services:
  nginx:
    image: referral_nginx_i
    build:
      context: .
      dockerfile: "./docker/Dockerfile.nginx"
    container_name: referral_nginx
    ports:
      - 80:80
      - 443:443
    links:
      - referral

  postgres-db:
    image: postgres:16
    container_name: referral_db
    env_file:
      - .env.prod
    # network_mode: host
    ports:
      - 5433:5432
    volumes:
      - referral_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: referral_redis
    # ports:
    #   - 6379:6379

  referral:
    image: referral_app_i
    build:
      context: .
    container_name: referral_app
    env_file:
      - .env.prod
    depends_on:
      - postgres-db
      - redis
    # ports:
    #   - 7777:8000
    # restart: always
                # command: bash -c "sleep 5 && alembic upgrade head && uvicorn app:create_app --factory --host 0.0.0.0"
    command: bash -c "./postgres_waiting.sh && alembic upgrade head && uvicorn app:create_app --factory --host 0.0.0.0"

volumes:
  referral_pg_data:
