"""Referrals

Revision ID: dff0300e2336
Revises: 19792d7102ce
Create Date: 2024-03-15 02:08:08.516751

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dff0300e2336"
down_revision = "19792d7102ce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("referrals", sa.Column("referral_id", sa.Integer(), nullable=False))
    op.add_column("referrals", sa.Column("referrer_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        "referrals_referral_code_id_fkey", "referrals", type_="foreignkey"
    )
    op.drop_constraint("referrals_user_id_fkey", "referrals", type_="foreignkey")
    op.create_foreign_key(None, "referrals", "users", ["referrer_id"], ["id"])
    op.create_foreign_key(None, "referrals", "users", ["referral_id"], ["id"])
    op.drop_column("referrals", "user_id")
    op.drop_column("referrals", "referral_code_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referrals",
        sa.Column(
            "referral_code_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "referrals",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "referrals", type_="foreignkey")
    op.drop_constraint(None, "referrals", type_="foreignkey")
    op.create_foreign_key(
        "referrals_user_id_fkey", "referrals", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "referrals_referral_code_id_fkey",
        "referrals",
        "referral_codes",
        ["referral_code_id"],
        ["id"],
    )
    op.drop_column("referrals", "referrer_id")
    op.drop_column("referrals", "referral_id")
    # ### end Alembic commands ###
